version: '3.4'

services:
  web:
    image: dockerclinic
    build:
      context: ./django_clinic
      dockerfile: ./Dockerfile
    command: gunicorn azyclinic.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./django_clinic:/app
    expose:
      - 8000                                                                     
    env_file:
      - ./django_clinic/.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8000:80
    depends_on:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
      - web

volumes:
  static_volume:
  media_volume: