# Generated by Django 3.0 on 2019-12-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicmanagement', '0002_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('address', models.CharField(max_length=200)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('services', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('cumulative_paid', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('payment_type', models.CharField(choices=[('CC', 'CREDIT CARD'), ('CA', 'CASH'), ('BT', 'BANK TRANSFER'), ('DC', 'DEBIT CARD')], default='CA', max_length=2)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmanagement.Patient')),
            ],
        ),
    ]
