# Generated by Django 3.0 on 2019-12-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_paid_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_on',
            field=models.DateField(verbose_name='Paid on'),
        ),
    ]
