# Generated by Django 3.0 on 2019-12-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20191230_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_on',
            field=models.DateField(blank=True, null=True, verbose_name='Paid on'),
        ),
    ]
