# Generated by Django 3.0 on 2019-12-31 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20191230_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.Service'),
        ),
    ]
