# Generated by Django 3.0 on 2019-12-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='services',
            field=models.CharField(max_length=220),
        ),
    ]
