# Generated by Django 3.0 on 2020-01-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20191231_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='procedure',
        ),
        migrations.AddField(
            model_name='invoice',
            name='procedure',
            field=models.ManyToManyField(to='invoices.Service'),
        ),
    ]
