# Generated by Django 3.0 on 2020-01-04 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_auto_20200104_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='procedure',
        ),
        migrations.AddField(
            model_name='invoice',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.Service'),
        ),
    ]
