# Generated by Django 3.0 on 2019-12-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicmanagement', '0002_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.TimeField(verbose_name='Appointment time')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('appointment_date', models.DateField(verbose_name='Appointment date')),
                ('is_checked_in', models.BooleanField()),
                ('is_cancelled', models.BooleanField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmanagement.Patient')),
            ],
        ),
    ]
