# Generated by Django 3.0 on 2019-12-09 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('eircode', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=12)),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
                ('GP_name', models.CharField(max_length=50)),
                ('GP_address', models.CharField(max_length=200)),
                ('next_of_kin_name', models.CharField(max_length=100)),
                ('next_of_kin_contact_number', models.CharField(max_length=12)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
