# Generated by Django 3.0 on 2019-12-30 10:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmanagement', '0003_auto_20191217_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='record',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='allergies',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='record',
            name='contraception',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='record',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='current_symptoms',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='date_of_clinic',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of clinic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='examination_today',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='further_plan',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='investigations_to_date',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='medical_history',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='medications',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='record',
            name='parity',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='referral_indication',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='smear',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='surgical_history',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='treatments_to_date',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
