# Generated by Django 3.0 on 2019-12-30 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmanagement', '0005_auto_20191230_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address_line_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='county',
            field=models.CharField(choices=[('Antrim', 'Antrim'), ('Armagh', 'ARMAGH'), ('Carlow', 'CARLOW'), ('Cavan', 'CAVAN'), ('Clare', 'CLARE'), ('Cork', 'CORK'), ('Derry', 'DERRY'), ('Donegal', 'DONEGAL'), ('Down', 'DOWN'), ('Dublin', 'DUBLIN'), ('Fermanagh', 'FERMANAGH'), ('Galway', 'GALWAY'), ('Kerry', 'KERRY'), ('Kildare', 'KILDARE'), ('Kilkenny', 'KILKENNY'), ('Laois', 'LAOIS'), ('Leitrim', 'LEITRIM'), ('Limerick', 'LIMERICK'), ('Longford', 'LONGFORD'), ('Louth', 'LOUTH'), ('Mayo', 'MAYO'), ('Meath', 'MEATH'), ('Monaghan', 'MONAGHAN'), ('Offaly', 'OFFALY'), ('Roscommon', 'ROSCOMMON'), ('Sligo', 'SLIGO'), ('Tipperary', 'TIPPERARY'), ('Tyrone', 'TYRONE'), ('Waterford', 'WATERFORD'), ('Westmeath', 'WESTMEATH'), ('Wexford', 'WEXFORD'), ('Wicklow', 'WICKLOW')], default='Waterford', max_length=12),
        ),
        migrations.AlterField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='clinicmanagement.Patient'),
        ),
    ]
