# Generated by Django 3.0 on 2019-12-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmanagement', '0006_auto_20191230_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='short_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
