# Generated by Django 3.0 on 2019-12-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmanagement', '0007_auto_20191230_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='eircode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
