# Generated by Django 3.0 on 2019-12-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmanagement', '0008_auto_20191231_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='county',
            field=models.CharField(choices=[('Antrim', 'ANTRIM'), ('Armagh', 'ARMAGH'), ('Carlow', 'CARLOW'), ('Cavan', 'CAVAN'), ('Clare', 'CLARE'), ('Cork', 'CORK'), ('Derry', 'DERRY'), ('Donegal', 'DONEGAL'), ('Down', 'DOWN'), ('Dublin', 'DUBLIN'), ('Fermanagh', 'FERMANAGH'), ('Galway', 'GALWAY'), ('Kerry', 'KERRY'), ('Kildare', 'KILDARE'), ('Kilkenny', 'KILKENNY'), ('Laois', 'LAOIS'), ('Leitrim', 'LEITRIM'), ('Limerick', 'LIMERICK'), ('Longford', 'LONGFORD'), ('Louth', 'LOUTH'), ('Mayo', 'MAYO'), ('Meath', 'MEATH'), ('Monaghan', 'MONAGHAN'), ('Offaly', 'OFFALY'), ('Roscommon', 'ROSCOMMON'), ('Sligo', 'SLIGO'), ('Tipperary', 'TIPPERARY'), ('Tyrone', 'TYRONE'), ('Waterford', 'WATERFORD'), ('Westmeath', 'WESTMEATH'), ('Wexford', 'WEXFORD'), ('Wicklow', 'WICKLOW')], default='Waterford', max_length=12),
        ),
    ]
