# Generated by Django 3.0 on 2020-01-21 18:10

import clinicmanagement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmanagement', '0009_auto_20191231_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maternity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MRN', models.CharField(max_length=10)),
                ('gestation_on_date_entered', models.IntegerField(default=0)),
                ('estimated_due_date', models.DateField(verbose_name='due date')),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_on', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maternity', to='clinicmanagement.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_file', models.FileField(upload_to=clinicmanagement.models.user_directory_path)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('description', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation', to='clinicmanagement.Patient')),
            ],
        ),
    ]
