# Generated by Django 3.0 on 2020-01-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmanagement', '0010_investigation_maternity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternity',
            name='delivered_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivered_on'),
        ),
    ]
