# Generated by Django 3.0 on 2020-01-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmanagement', '0011_auto_20200126_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternity',
            name='gestation_on_date_entered',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
